Homework ini merupakan tugas individu dan ditujukan untuk melatih dan mengukur pemahaman teman-teman terhadap konsep 

pada materi Introduction to Data Engineering:

Scrape semua element (judul pekerjaan, nama perusahaan, tanggal job posting) dari website berikut 

https://realpython.github.io/fake-jobs/  menggunakan BeautifulSoup dan simpan data tersebut kedalam csv file.

In [2]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup
from requests import get

In [3]:
url = "https://realpython.github.io/fake-jobs/"
html = urlopen(url)

In [4]:
soup = BeautifulSoup(html, 'lxml')

## Extract Nama Pekerjaan

In [5]:
job = soup.find_all('h2', class_='title is-5')
job

[<h2 class="title is-5">Senior Python Developer</h2>,
 <h2 class="title is-5">Energy engineer</h2>,
 <h2 class="title is-5">Legal executive</h2>,
 <h2 class="title is-5">Fitness centre manager</h2>,
 <h2 class="title is-5">Product manager</h2>,
 <h2 class="title is-5">Medical technical officer</h2>,
 <h2 class="title is-5">Physiological scientist</h2>,
 <h2 class="title is-5">Textile designer</h2>,
 <h2 class="title is-5">Television floor manager</h2>,
 <h2 class="title is-5">Waste management officer</h2>,
 <h2 class="title is-5">Software Engineer (Python)</h2>,
 <h2 class="title is-5">Interpreter</h2>,
 <h2 class="title is-5">Architect</h2>,
 <h2 class="title is-5">Meteorologist</h2>,
 <h2 class="title is-5">Audiological scientist</h2>,
 <h2 class="title is-5">English as a second language teacher</h2>,
 <h2 class="title is-5">Surgeon</h2>,
 <h2 class="title is-5">Equities trader</h2>,
 <h2 class="title is-5">Newspaper journalist</h2>,
 <h2 class="title is-5">Materials engineer</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Product/process development scientist</h2>,
 <h2 class="title is-5">Scientist, research (maths)</h2>,
 <h2 class="title is-5">Ecologist</h2>,
 <h2 class="title is-5">Materials engineer</h2>,
 <h2 class="title is-5">Historic buildings inspector/conservation officer</h2>,
 <h2 class="title is-5">Data scientist</h2>,
 <h2 class="title is-5">Psychiatrist</h2>,
 <h2 class="title is-5">Structural engineer</h2>,
 <h2 class="title is-5">Immigration officer</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Neurosurgeon</h2>,
 <h2 class="title is-5">Broadcast engineer</h2>,
 <h2 class="title is-5">Make</h2>,
 <h2 class="title is-5">Nurse, adult</h2>,
 <h2 class="title is-5">Air broker</h2>,
 <h2 class="title is-5">Editor, film/video</h2>,
 <h2 class="title is-5">Production assistant, radio</h2>,
 <h2 class="title is-5">Engineer, communications</h2>,
 <h2 class="title is-5">Sales executive</h2>,
 <h2 class="title is-5">Software Developer (Python)</h2>,
 <h2 class="title is-5">Futures trader</h2>,
 <h2 class="title is-5">Tour manager</h2>,
 <h2 class="title is-5">Cytogeneticist</h2>,
 <h2 class="title is-5">Designer, multimedia</h2>,
 <h2 class="title is-5">Trade union research officer</h2>,
 <h2 class="title is-5">Chemist, analytical</h2>,
 <h2 class="title is-5">Programmer, multimedia</h2>,
 <h2 class="title is-5">Engineer, broadcasting (operations)</h2>,
 <h2 class="title is-5">Teacher, primary school</h2>,
 <h2 class="title is-5">Python Developer</h2>,
 <h2 class="title is-5">Manufacturing systems engineer</h2>,
 <h2 class="title is-5">Producer, television/film/video</h2>,
 <h2 class="title is-5">Scientist, forensic</h2>,
 <h2 class="title is-5">Bonds trader</h2>,
 <h2 class="title is-5">Editorial assistant</h2>,
 <h2 class="title is-5">Photographer</h2>,
 <h2 class="title is-5">Retail banker</h2>,
 <h2 class="title is-5">Jewellery designer</h2>,
 <h2 class="title is-5">Ophthalmologist</h2>,
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>,
 <h2 class="title is-5">Licensed conveyancer</h2>,
 <h2 class="title is-5">Futures trader</h2>,
 <h2 class="title is-5">Counselling psychologist</h2>,
 <h2 class="title is-5">Insurance underwriter</h2>,
 <h2 class="title is-5">Engineer, automotive</h2>,
 <h2 class="title is-5">Producer, radio</h2>,
 <h2 class="title is-5">Dispensing optician</h2>,
 <h2 class="title is-5">Designer, fashion/clothing</h2>,
 <h2 class="title is-5">Chartered loss adjuster</h2>,
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>,
 <h2 class="title is-5">Forest/woodland manager</h2>,
 <h2 class="title is-5">Clinical cytogeneticist</h2>,
 <h2 class="title is-5">Print production planner</h2>,
 <h2 class="title is-5">Systems developer</h2>,
 <h2 class="title is-5">Graphic designer</h2>,
 <h2 class="title is-5">Writer</h2>,
 <h2 class="title is-5">Field seismologist</h2>,
 <h2 class="title is-5">Chief Strategy Officer</h2>,
 <h2 class="title is-5">Air cabin crew</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Warden/ranger</h2>,
 <h2 class="title is-5">Sports therapist</h2>,
 <h2 class="title is-5">Arts development officer</h2>,
 <h2 class="title is-5">Printmaker</h2>,
 <h2 class="title is-5">Health and safety adviser</h2>,
 <h2 class="title is-5">Manufacturing systems engineer</h2>,
 <h2 class="title is-5">Programmer, applications</h2>,
 <h2 class="title is-5">Medical physicist</h2>,
 <h2 class="title is-5">Media planner</h2>,
 <h2 class="title is-5">Software Developer (Python)</h2>,
 <h2 class="title is-5">Surveyor, land/geomatics</h2>,
 <h2 class="title is-5">Legal executive</h2>,
 <h2 class="title is-5">Librarian, academic</h2>,
 <h2 class="title is-5">Barrister</h2>,
 <h2 class="title is-5">Museum/gallery exhibitions officer</h2>,
 <h2 class="title is-5">Radiographer, diagnostic</h2>,
 <h2 class="title is-5">Database administrator</h2>,
 <h2 class="title is-5">Furniture designer</h2>,
 <h2 class="title is-5">Ship broker</h2>]

In [6]:
list_job = []

for j in job:
    list_job.append(j.text)

list_job

['Senior Python Developer',
 'Energy engineer',
 'Legal executive',
 'Fitness centre manager',
 'Product manager',
 'Medical technical officer',
 'Physiological scientist',
 'Textile designer',
 'Television floor manager',
 'Waste management officer',
 'Software Engineer (Python)',
 'Interpreter',
 'Architect',
 'Meteorologist',
 'Audiological scientist',
 'English as a second language teacher',
 'Surgeon',
 'Equities trader',
 'Newspaper journalist',
 'Materials engineer',
 'Python Programmer (Entry-Level)',
 'Product/process development scientist',
 'Scientist, research (maths)',
 'Ecologist',
 'Materials engineer',
 'Historic buildings inspector/conservation officer',
 'Data scientist',
 'Psychiatrist',
 'Structural engineer',
 'Immigration officer',
 'Python Programmer (Entry-Level)',
 'Neurosurgeon',
 'Broadcast engineer',
 'Make',
 'Nurse, adult',
 'Air broker',
 'Editor, film/video',
 'Production assistant, radio',
 'Engineer, communications',
 'Sales executive',
 'Software Developer (Python)',
 'Futures trader',
 'Tour manager',
 'Cytogeneticist',
 'Designer, multimedia',
 'Trade union research officer',
 'Chemist, analytical',
 'Programmer, multimedia',
 'Engineer, broadcasting (operations)',
 'Teacher, primary school',
 'Python Developer',
 'Manufacturing systems engineer',
 'Producer, television/film/video',
 'Scientist, forensic',
 'Bonds trader',
 'Editorial assistant',
 'Photographer',
 'Retail banker',
 'Jewellery designer',
 'Ophthalmologist',
 'Back-End Web Developer (Python, Django)',
 'Licensed conveyancer',
 'Futures trader',
 'Counselling psychologist',
 'Insurance underwriter',
 'Engineer, automotive',
 'Producer, radio',
 'Dispensing optician',
 'Designer, fashion/clothing',
 'Chartered loss adjuster',
 'Back-End Web Developer (Python, Django)',
 'Forest/woodland manager',
 'Clinical cytogeneticist',
 'Print production planner',
 'Systems developer',
 'Graphic designer',
 'Writer',
 'Field seismologist',
 'Chief Strategy Officer',
 'Air cabin crew',
 'Python Programmer (Entry-Level)',
 'Warden/ranger',
 'Sports therapist',
 'Arts development officer',
 'Printmaker',
 'Health and safety adviser',
 'Manufacturing systems engineer',
 'Programmer, applications',
 'Medical physicist',
 'Media planner',
 'Software Developer (Python)',
 'Surveyor, land/geomatics',
 'Legal executive',
 'Librarian, academic',
 'Barrister',
 'Museum/gallery exhibitions officer',
 'Radiographer, diagnostic',
 'Database administrator',
 'Furniture designer',
 'Ship broker']

## Extract Nama Perusahaan

In [7]:
company = soup.find_all('h3', class_='subtitle is-6 company')
company

[<h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>,
 <h3 class="subtitle is-6 company">Vasquez-Davidson</h3>,
 <h3 class="subtitle is-6 company">Jackson, Chambers and Levy</h3>,
 <h3 class="subtitle is-6 company">Savage-Bradley</h3>,
 <h3 class="subtitle is-6 company">Ramirez Inc</h3>,
 <h3 class="subtitle is-6 company">Rogers-Yates</h3>,
 <h3 class="subtitle is-6 company">Kramer-Klein</h3>,
 <h3 class="subtitle is-6 company">Meyers-Johnson</h3>,
 <h3 class="subtitle is-6 company">Hughes-Williams</h3>,
 <h3 class="subtitle is-6 company">Jones, Williams and Villa</h3>,
 <h3 class="subtitle is-6 company">Garcia PLC</h3>,
 <h3 class="subtitle is-6 company">Gregory and Sons</h3>,
 <h3 class="subtitle is-6 company">Clark, Garcia and Sosa</h3>,
 <h3 class="subtitle is-6 company">Bush PLC</h3>,
 <h3 class="subtitle is-6 company">Salazar-Meyers</h3>,
 <h3 class="subtitle is-6 company">Parker, Murphy and Brooks</h3>,
 <h3 class="subtitle is-6 company">Cruz-Brown</h3>,
 <h3 class="subtitle is-6 company">Macdonald-Ferguson</h3>,
 <h3 class="subtitle is-6 company">Williams, Peterson and Rojas</h3>,
 <h3 class="subtitle is-6 company">Smith and Sons</h3>,
 <h3 class="subtitle is-6 company">Moss, Duncan and Allen</h3>,
 <h3 class="subtitle is-6 company">Gomez-Carroll</h3>,
 <h3 class="subtitle is-6 company">Manning, Welch and Herring</h3>,
 <h3 class="subtitle is-6 company">Lee, Gutierrez and Brown</h3>,
 <h3 class="subtitle is-6 company">Davis, Serrano and Cook</h3>,
 <h3 class="subtitle is-6 company">Smith LLC</h3>,
 <h3 class="subtitle is-6 company">Thomas Group</h3>,
 <h3 class="subtitle is-6 company">Silva-King</h3>,
 <h3 class="subtitle is-6 company">Pierce-Long</h3>,
 <h3 class="subtitle is-6 company">Walker-Simpson</h3>,
 <h3 class="subtitle is-6 company">Cooper and Sons</h3>,
 <h3 class="subtitle is-6 company">Donovan, Gonzalez and Figueroa</h3>,
 <h3 class="subtitle is-6 company">Morgan, Butler and Bennett</h3>,
 <h3 class="subtitle is-6 company">Snyder-Lee</h3>,
 <h3 class="subtitle is-6 company">Harris PLC</h3>,
 <h3 class="subtitle is-6 company">Washington PLC</h3>,
 <h3 class="subtitle is-6 company">Brown, Price and Campbell</h3>,
 <h3 class="subtitle is-6 company">Mcgee PLC</h3>,
 <h3 class="subtitle is-6 company">Dixon Inc</h3>,
 <h3 class="subtitle is-6 company">Thompson, Sheppard and Ward</h3>,
 <h3 class="subtitle is-6 company">Adams-Brewer</h3>,
 <h3 class="subtitle is-6 company">Schneider-Brady</h3>,
 <h3 class="subtitle is-6 company">Gonzales-Frank</h3>,
 <h3 class="subtitle is-6 company">Smith-Wong</h3>,
 <h3 class="subtitle is-6 company">Pierce-Herrera</h3>,
 <h3 class="subtitle is-6 company">Aguilar, Rivera and Quinn</h3>,
 <h3 class="subtitle is-6 company">Lowe, Barnes and Thomas</h3>,
 <h3 class="subtitle is-6 company">Lewis, Gonzalez and Vasquez</h3>,
 <h3 class="subtitle is-6 company">Taylor PLC</h3>,
 <h3 class="subtitle is-6 company">Oliver, Jones and Ramirez</h3>,
 <h3 class="subtitle is-6 company">Rivera and Sons</h3>,
 <h3 class="subtitle is-6 company">Garcia PLC</h3>,
 <h3 class="subtitle is-6 company">Johnson, Wells and Kramer</h3>,
 <h3 class="subtitle is-6 company">Gonzalez LLC</h3>,
 <h3 class="subtitle is-6 company">Morgan, White and Macdonald</h3>,
 <h3 class="subtitle is-6 company">Robinson-Fitzpatrick</h3>,
 <h3 class="subtitle is-6 company">Waters, Wilson and Hoover</h3>,
 <h3 class="subtitle is-6 company">Hill LLC</h3>,
 <h3 class="subtitle is-6 company">Li-Gregory</h3>,
 <h3 class="subtitle is-6 company">Fisher, Ryan and Coleman</h3>,
 <h3 class="subtitle is-6 company">Stewart-Alexander</h3>,
 <h3 class="subtitle is-6 company">Abbott and Sons</h3>,
 <h3 class="subtitle is-6 company">Bryant, Santana and Davenport</h3>,
 <h3 class="subtitle is-6 company">Smith PLC</h3>,
 <h3 class="subtitle is-6 company">Patterson-Singh</h3>,
 <h3 class="subtitle is-6 company">Martinez-Berry</h3>,
 <h3 class="subtitle is-6 company">May, Taylor and Fisher</h3>,
 <h3 class="subtitle is-6 company">Bailey, Owen and Thompson</h3>,
 <h3 class="subtitle is-6 company">Vasquez Ltd</h3>,
 <h3 class="subtitle is-6 company">Leblanc LLC</h3>,
 <h3 class="subtitle is-6 company">Jackson, Ali and Mckee</h3>,
 <h3 class="subtitle is-6 company">Blankenship, Knight and Powell</h3>,
 <h3 class="subtitle is-6 company">Patton, Haynes and Jones</h3>,
 <h3 class="subtitle is-6 company">Wood Inc</h3>,
 <h3 class="subtitle is-6 company">Collins Group</h3>,
 <h3 class="subtitle is-6 company">Flores-Nelson</h3>,
 <h3 class="subtitle is-6 company">Mitchell, Jones and Olson</h3>,
 <h3 class="subtitle is-6 company">Howard Group</h3>,
 <h3 class="subtitle is-6 company">Kramer-Edwards</h3>,
 <h3 class="subtitle is-6 company">Berry-Houston</h3>,
 <h3 class="subtitle is-6 company">Mathews Inc</h3>,
 <h3 class="subtitle is-6 company">Riley-Johnson</h3>,
 <h3 class="subtitle is-6 company">Spencer and Sons</h3>,
 <h3 class="subtitle is-6 company">Camacho-Sanchez</h3>,
 <h3 class="subtitle is-6 company">Oliver and Sons</h3>,
 <h3 class="subtitle is-6 company">Eaton PLC</h3>,
 <h3 class="subtitle is-6 company">Stanley-Frederick</h3>,
 <h3 class="subtitle is-6 company">Bradley LLC</h3>,
 <h3 class="subtitle is-6 company">Parker, Goodwin and Zavala</h3>,
 <h3 class="subtitle is-6 company">Kim-Miles</h3>,
 <h3 class="subtitle is-6 company">Moreno-Rodriguez</h3>,
 <h3 class="subtitle is-6 company">Brown-Ortiz</h3>,
 <h3 class="subtitle is-6 company">Hartman PLC</h3>,
 <h3 class="subtitle is-6 company">Brooks Inc</h3>,
 <h3 class="subtitle is-6 company">Washington-Castillo</h3>,
 <h3 class="subtitle is-6 company">Nguyen, Yoder and Petty</h3>,
 <h3 class="subtitle is-6 company">Holder LLC</h3>,
 <h3 class="subtitle is-6 company">Yates-Ferguson</h3>,
 <h3 class="subtitle is-6 company">Ortega-Lawrence</h3>,
 <h3 class="subtitle is-6 company">Fuentes, Walls and Castro</h3>]

In [8]:
list_company = []

for c in company:
    list_company.append(c.text)

list_company

['Payne, Roberts and Davis',
 'Vasquez-Davidson',
 'Jackson, Chambers and Levy',
 'Savage-Bradley',
 'Ramirez Inc',
 'Rogers-Yates',
 'Kramer-Klein',
 'Meyers-Johnson',
 'Hughes-Williams',
 'Jones, Williams and Villa',
 'Garcia PLC',
 'Gregory and Sons',
 'Clark, Garcia and Sosa',
 'Bush PLC',
 'Salazar-Meyers',
 'Parker, Murphy and Brooks',
 'Cruz-Brown',
 'Macdonald-Ferguson',
 'Williams, Peterson and Rojas',
 'Smith and Sons',
 'Moss, Duncan and Allen',
 'Gomez-Carroll',
 'Manning, Welch and Herring',
 'Lee, Gutierrez and Brown',
 'Davis, Serrano and Cook',
 'Smith LLC',
 'Thomas Group',
 'Silva-King',
 'Pierce-Long',
 'Walker-Simpson',
 'Cooper and Sons',
 'Donovan, Gonzalez and Figueroa',
 'Morgan, Butler and Bennett',
 'Snyder-Lee',
 'Harris PLC',
 'Washington PLC',
 'Brown, Price and Campbell',
 'Mcgee PLC',
 'Dixon Inc',
 'Thompson, Sheppard and Ward',
 'Adams-Brewer',
 'Schneider-Brady',
 'Gonzales-Frank',
 'Smith-Wong',
 'Pierce-Herrera',
 'Aguilar, Rivera and Quinn',
 'Lowe, Barnes and Thomas',
 'Lewis, Gonzalez and Vasquez',
 'Taylor PLC',
 'Oliver, Jones and Ramirez',
 'Rivera and Sons',
 'Garcia PLC',
 'Johnson, Wells and Kramer',
 'Gonzalez LLC',
 'Morgan, White and Macdonald',
 'Robinson-Fitzpatrick',
 'Waters, Wilson and Hoover',
 'Hill LLC',
 'Li-Gregory',
 'Fisher, Ryan and Coleman',
 'Stewart-Alexander',
 'Abbott and Sons',
 'Bryant, Santana and Davenport',
 'Smith PLC',
 'Patterson-Singh',
 'Martinez-Berry',
 'May, Taylor and Fisher',
 'Bailey, Owen and Thompson',
 'Vasquez Ltd',
 'Leblanc LLC',
 'Jackson, Ali and Mckee',
 'Blankenship, Knight and Powell',
 'Patton, Haynes and Jones',
 'Wood Inc',
 'Collins Group',
 'Flores-Nelson',
 'Mitchell, Jones and Olson',
 'Howard Group',
 'Kramer-Edwards',
 'Berry-Houston',
 'Mathews Inc',
 'Riley-Johnson',
 'Spencer and Sons',
 'Camacho-Sanchez',
 'Oliver and Sons',
 'Eaton PLC',
 'Stanley-Frederick',
 'Bradley LLC',
 'Parker, Goodwin and Zavala',
 'Kim-Miles',
 'Moreno-Rodriguez',
 'Brown-Ortiz',
 'Hartman PLC',
 'Brooks Inc',
 'Washington-Castillo',
 'Nguyen, Yoder and Petty',
 'Holder LLC',
 'Yates-Ferguson',
 'Ortega-Lawrence',
 'Fuentes, Walls and Castro']

## Extract Tanggal Publish

In [9]:
date = soup.find_all('time')
date

[<time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>]

In [10]:
list_date = []

for d in date:
    list_date.append(d.text)

list_date

['2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08']

## Membuat dataframe untuk data yang sudah di scarping

In [11]:
df = pd.DataFrame({
                   'job' : list_job,
                   'company' : list_company,
                   'date' : list_date
                   })

df

                                   job                     company        date
0              Senior Python Developer    Payne, Roberts and Davis  2021-04-08
1                      Energy engineer            Vasquez-Davidson  2021-04-08
2                      Legal executive  Jackson, Chambers and Levy  2021-04-08
3               Fitness centre manager              Savage-Bradley  2021-04-08
4                      Product manager                 Ramirez Inc  2021-04-08
..                                 ...                         ...         ...
95  Museum/gallery exhibitions officer     Nguyen, Yoder and Petty  2021-04-08
96            Radiographer, diagnostic                  Holder LLC  2021-04-08
97              Database administrator              Yates-Ferguson  2021-04-08
98                  Furniture designer             Ortega-Lawrence  2021-04-08
99                         Ship broker   Fuentes, Walls and Castro  2021-04-08

[100 rows x 3 columns]

## Tranformasi tambah kolom ID

In [12]:
from uuid import uuid4
import uuid

df['uuid'] = [uuid.uuid4() for _ in range(len(df.index))]
df = df[['uuid','job','company','date']]
df

,uuid,job,company,date
0,6688d49f-e50b-4f4e-9b11-db35ed5d7731,Senior Python Developer,"Payne, Roberts and Davis",2021-04-08
1,6bbcca45-a6f4-47a9-8162-ac8864087628,Energy engineer,Vasquez-Davidson,2021-04-08
2,48f917dc-eea8-44eb-b92a-78a196c08e2c,Legal executive,"Jackson, Chambers and Levy",2021-04-08
3,f944efdb-5f61-4d22-99a9-0c839fe66342,Fitness centre manager,Savage-Bradley,2021-04-08
4,76b11be9-50bf-4883-a8c0-a032fd0b415b,Product manager,Ramirez Inc,2021-04-08
...,...,...,...,...
95,ec44cb64-8b77-4d95-bee8-0dee38c53236,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty",2021-04-08
96,06a5bb0d-284b-4733-a883-c6e2c2543d99,"Radiographer, diagnostic",Holder LLC,2021-04-08
97,9a958653-cda9-4578-a583-198a56baf775,Database administrator,Yates-Ferguson,2021-04-08
98,062853db-911a-4043-8bf5-37cb19db164a,Furniture designer,Ortega-Lawrence,2021-04-08
99,7c00d2cc-57c3-41b8-9b5a-f81ddb69bf72,Ship broker,"Fuentes, Walls and Castro",2021-04-08

## Masukin data ke CSV

In [13]:
df.to_csv('Web Scraping.csv', index = False)